"""
qmt_trade_wrapper.py

Wrapper for scripts dropped into the QMT hot-folder for execution by the
miniQMT embedded python engine (xtquant).

Design goals (per Sha's requirements):
  1. GUARD: before submitting an order, check current positions. If the
     target position already exists (or is already sufficiently sized),
     skip execution rather than risk a duplicate/unwanted trade.
  2. REPORT: after execution, query orders/trades and write a JSON result
     file to a `results/` folder that the sync tool mirrors back to the
     Mac side, so the orchestrator gets a real success/fail/partial signal
     instead of inferring from file deletion.
  3. WAIT: because A-share settlement (T+0 volume vs T+1 can_use_volume)
     and position refresh are not instant, wait a configurable delay
     before the post-trade position query, and optionally poll a few times.

This module is meant to be IMPORTED by the actual per-trade scripts you
drop into the hot folder (e.g. generated by executor.py), not run
standalone. Each dropped script should:

    from qmt_trade_wrapper import TradeGuard

    guard = TradeGuard(xt_trader, acc, task_id="20260715_600519_buy")
    guard.run(
        code="600519.SH",
        direction="buy",
        volume=100,
        price=None,           # None = market/latest-price order, or set limit price
        min_existing_volume=1 # skip if already holding >= this many shares
    )

Adjust the xtquant call signatures below if your installed xtquant version
differs (order_stock / query_stock_positions / query_stock_orders /
query_stock_trades are the standard miniQMT trader API names as of recent
QMT releases -- verify against your local xtquant docs/version if calls
fail, since brokers sometimes ship slightly patched builds).
"""

import json
import os
import time
import traceback
from datetime import datetime

# ---------------------------------------------------------------------------
# Config -- adjust paths to match your synced folder layout
# ---------------------------------------------------------------------------

RESULTS_DIR = os.environ.get("QMT_RESULTS_DIR", r"C:\QMT_Sync\results")
DEFAULT_POST_TRADE_WAIT_SEC = 8      # initial wait before first post-check
DEFAULT_POLL_INTERVAL_SEC = 5        # gap between subsequent polls
DEFAULT_MAX_POLLS = 4                # how many times to re-check if still pending

os.makedirs(RESULTS_DIR, exist_ok=True)


def _now_iso():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _write_result(task_id, payload):
    """Write the result JSON that gets synced back to the Mac side."""
    payload["task_id"] = task_id
    payload["written_at"] = _now_iso()
    path = os.path.join(RESULTS_DIR, f"{task_id}.json")
    tmp_path = path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    os.replace(tmp_path, path)  # atomic-ish write so sync tool never sees a half file
    return path


class TradeGuard:
    def __init__(self, xt_trader, account, task_id):
        """
        xt_trader: an already-connected XtQuantTrader instance
        account:   the StockAccount object for the target account
        task_id:   unique string identifying this trade task, ideally derived
                   from the dropped filename so results correlate 1:1
        """
        self.xt_trader = xt_trader
        self.account = account
        self.task_id = task_id

    # -- position helpers ---------------------------------------------------

    def _get_positions(self):
        """Returns list of position objects for the account."""
        return self.xt_trader.query_stock_positions(self.account) or []

    def _find_position(self, code):
        for p in self._get_positions():
            # xtquant position objects expose .stock_code
            if getattr(p, "stock_code", None) == code:
                return p
        return None

    def _position_snapshot(self, code):
        pos = self._find_position(code)
        if pos is None:
            return {"volume": 0, "can_use_volume": 0, "avg_price": None, "market_value": None}
        return {
            "volume": getattr(pos, "volume", 0),
            "can_use_volume": getattr(pos, "can_use_volume", 0),
            "avg_price": getattr(pos, "open_price", None),
            "market_value": getattr(pos, "market_value", None),
        }

    # -- order helpers --------------------------------------------------

    def _query_order_status(self, order_id):
        orders = self.xt_trader.query_stock_orders(self.account) or []
        for o in orders:
            if getattr(o, "order_id", None) == order_id:
                return o
        return None

    def _query_trades_for_order(self, order_id):
        trades = self.xt_trader.query_stock_trades(self.account) or []
        return [t for t in trades if getattr(t, "order_id", None) == order_id]

    # -- main entry point -----------------------------------------------

    def run(
        self,
        code,
        direction,           # "buy" or "sell"
        volume,
        price=None,
        min_existing_volume=1,
        skip_guard=False,
        post_trade_wait_sec=DEFAULT_POST_TRADE_WAIT_SEC,
        poll_interval_sec=DEFAULT_POLL_INTERVAL_SEC,
        max_polls=DEFAULT_MAX_POLLS,
        price_type=None,      # override the default LATEST_PRICE/FIX_PRICE choice,
                               # e.g. xtconstant.MARKET_SH_CONVERT_5_CANCEL for A-share
                               # exchange-specific market orders
    ):
        result = {
            "code": code,
            "direction": direction,
            "requested_volume": volume,
            "price": price,
        }

        try:
            # ---- Step 1: pre-trade guard ----
            before = self._position_snapshot(code)
            result["position_before"] = before

            if not skip_guard and direction == "buy" and before["volume"] >= min_existing_volume:
                result["status"] = "SKIPPED_ALREADY_HELD"
                result["detail"] = (
                    f"Existing volume {before['volume']} >= min_existing_volume "
                    f"{min_existing_volume}; not submitting duplicate buy."
                )
                _write_result(self.task_id, result)
                return result

            if not skip_guard and direction == "sell" and before["can_use_volume"] <= 0:
                result["status"] = "SKIPPED_NOTHING_TO_SELL"
                result["detail"] = "No usable position to sell (can_use_volume <= 0)."
                _write_result(self.task_id, result)
                return result

            # ---- Step 2: submit order ----
            # xtquant order type constants: adjust import to your local xtquant version
            from xtquant import xtconstant

            order_type = (
                xtconstant.STOCK_BUY if direction == "buy" else xtconstant.STOCK_SELL
            )
            if price_type is None:
                price_type = (
                    xtconstant.LATEST_PRICE if price is None else xtconstant.FIX_PRICE
                )

            order_id = self.xt_trader.order_stock(
                self.account,
                code,
                order_type,
                volume,
                price_type,
                price if price is not None else 0,
            )
            result["order_id"] = order_id
            result["submitted_at"] = _now_iso()

            if order_id is None or order_id < 0:
                result["status"] = "SUBMIT_FAILED"
                result["detail"] = "order_stock returned no/invalid order_id."
                _write_result(self.task_id, result)
                return result

            # ---- Step 3: wait, then verify ----
            time.sleep(post_trade_wait_sec)

            order_status = None
            trades = []
            for attempt in range(max_polls):
                order_status = self._query_order_status(order_id)
                trades = self._query_trades_for_order(order_id)
                status_code = getattr(order_status, "order_status", None) if order_status else None
                # Common xtquant terminal statuses: filled / cancelled / rejected
                # Keep polling only if still pending/partial
                if status_code in (None,) or getattr(order_status, "order_status", None) in (
                    getattr(__import__("xtquant.xtconstant", fromlist=["xtconstant"]), "ORDER_UNREPORTED", None),
                    getattr(__import__("xtquant.xtconstant", fromlist=["xtconstant"]), "ORDER_REPORTED", None),
                ):
                    time.sleep(poll_interval_sec)
                    continue
                break

            after = self._position_snapshot(code)
            result["position_after"] = after
            result["volume_delta"] = after["volume"] - before["volume"]

            result["order_status_raw"] = getattr(order_status, "order_status", None)
            result["filled_volume"] = getattr(order_status, "traded_volume", None) if order_status else None
            result["trade_count"] = len(trades)
            result["error_msg"] = getattr(order_status, "status_msg", None) if order_status else None

            if result["filled_volume"] and result["filled_volume"] > 0:
                if result["filled_volume"] >= volume:
                    result["status"] = "FILLED"
                else:
                    result["status"] = "PARTIAL_FILL"
            elif result["volume_delta"] != 0:
                # position moved even though order status lookup was ambiguous
                result["status"] = "FILLED_INFERRED_FROM_POSITION"
            else:
                result["status"] = "NO_FILL_DETECTED"

        except Exception as e:
            result["status"] = "ERROR"
            result["detail"] = str(e)
            result["traceback"] = traceback.format_exc()

        _write_result(self.task_id, result)
        return result
